#!/bin/bash
set -eu

function usage() {
    echo -n \
"Usage: $(basename "$0")
Use Docker Compose to enter a psql shell on the local database container
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1:-}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[pgsockets4s] Starting dbshell...\e[0m"
            docker-compose run --rm -e PGPASSWORD=pgsockets4s database psql -U pgsockets4s -h database
            ;;
    esac
fi
