#!/bin/bash

set -e

function usage() {
    echo -n \
         "Usage: $(basename "$0") short-desc

Create a new migration, with the current timestamp and short-desc description
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        cat > \
            "migrations/$(date --iso-8601=seconds -u | rev | cut -c 7- | rev)_${1}.sql" \
            <<EOF
-- rambler up

CREATE TABLE 'foo';

-- rambler down

DROP TABLE 'foo';

EOF


    fi
fi
