#!/bin/bash

set -e


if [[ -n "${PGSOCKETS4S_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Setup external project dependencies.
"
}


if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo -e "\e[32m[pgsockets4s] Configuring bloop...\e[0m"
            sbt ";bloopInstall; scalafmt; scalafmtSbt"
            docker-compose up -d database
            ./scripts/migrate
    esac
fi
